import { StyleSheet, Dimensions } from 'react-native';

export const { width } = Dimensions.get('window');

export const COLORS = {
  primary: '#864AF9',
  background: '#F8F9FE',
  cardBg: '#FFFFFF',
  itemBg: '#F7F9FC',
  textDark: '#2D3748',
  textLight: '#718096',
  textWhite: '#FFFFFF',
  black: '#000000',
  success: '#C6F6D5',
  successText: '#065F46',
  border: '#000000',
};

export const sharedStyles = {
  hardShadow: {
    shadowColor: COLORS.black,
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  cardBase: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: COLORS.border,
    padding: 20,
    marginBottom: 20,
  },
};

export const sponsorBannerStyles = StyleSheet.create({
  container: { flexDirection: 'row', backgroundColor: '#FFFFFF', borderRadius: 15, padding: 15, marginBottom: 20, borderWidth: 2, borderColor: '#864AF9', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  photo: { width: 70, height: 70, borderRadius: 35, borderWidth: 3, borderColor: '#864AF9', marginRight: 12 },
  content: { flex: 1, justifyContent: 'center' },
  header: { flexDirection: 'row', alignItems: 'center', marginBottom: 5 },
  badge: { fontSize: 10, fontWeight: '800', color: '#10B981', marginLeft: 5, letterSpacing: 0.5 },
  sponsorText: { fontSize: 13, color: '#6B7280', marginBottom: 3 },
  politicianName: { fontWeight: '700', color: '#864AF9', fontSize: 14 },
  position: { fontSize: 12, color: '#9CA3AF', marginBottom: 8 },
  expiryContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F3F4F6', paddingVertical: 5, paddingHorizontal: 8, borderRadius: 8, alignSelf: 'flex-start' },
  expiryWarning: { backgroundColor: '#FEE2E2' },
  expiryText: { fontSize: 11, color: '#6B7280', marginLeft: 5, fontWeight: '600' },
  expiryTextWarning: { color: '#DC2626' },
});

const styles = StyleSheet.create({
  container: { backgroundColor: COLORS.background, padding: 16, paddingBottom: 100 },
  mainWrapper: { flex: 1, backgroundColor: COLORS.background },
  headerContainer: { marginBottom: 25 },
  // TOP TABS
  topTabContainer: { flexDirection: 'row', backgroundColor: COLORS.cardBg, padding: 6, margin: 16, borderRadius: 16, borderWidth: 3, borderColor: COLORS.border, shadowColor: COLORS.black, shadowOffset: { width: 4, height: 4 }, shadowOpacity: 1, shadowRadius: 0, elevation: 4 },
  topTab: { flex: 1, paddingVertical: 12, alignItems: 'center', borderRadius: 12, borderWidth: 2, borderColor: 'transparent' },
  activeTopTab: { backgroundColor: COLORS.primary, borderColor: COLORS.border },
  topTabText: { fontSize: 15, fontWeight: '700', color: COLORS.textLight },
  activeTopTabText: { color: COLORS.textWhite, fontWeight: '900' },
  // INFO / PROFILE CARD
  infoContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: COLORS.primary, padding: 20, borderRadius: 20, marginBottom: 16, borderWidth: 2, borderColor: COLORS.border, shadowColor: COLORS.black, shadowOffset: { width: 4, height: 4 }, shadowOpacity: 1, shadowRadius: 0, elevation: 4 },
  leftInfo: { flex: 1 },
  hello: { color: 'rgba(255,255,255,0.9)', fontSize: 16, fontWeight: '600' },
  infoUsername: { color: '#FFFFFF', fontSize: 28, fontWeight: '900', letterSpacing: 0.5 },
  infoAvatar: { width: 64, height: 64, borderRadius: 32, borderWidth: 3, borderColor: '#FFFFFF' },
  // STREAKS
  streaksContainer: { backgroundColor: COLORS.cardBg, borderRadius: 20, padding: 20, marginBottom: 16, borderWidth: 2, borderColor: COLORS.border, shadowColor: COLORS.black, shadowOffset: { width: 4, height: 4 }, shadowOpacity: 1, shadowRadius: 0, elevation: 4, alignItems: 'center' },
  streaksTitle: { fontSize: 18, fontWeight: '800', color: COLORS.textDark, marginBottom: 8 },
  streaksCount: { fontSize: 48, fontWeight: '900', color: COLORS.primary },
  // REPORTS
  reportsContainer: { backgroundColor: COLORS.cardBg, borderRadius: 20, padding: 20, marginBottom: 16, borderWidth: 2, borderColor: COLORS.border, shadowColor: COLORS.black, shadowOffset: { width: 4, height: 4 }, shadowOpacity: 1, shadowRadius: 0, elevation: 4 },
  title: { fontSize: 20, fontWeight: '900', color: COLORS.textDark, marginBottom: 16 },
  reportItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: COLORS.itemBg, padding: 14, marginBottom: 10, borderRadius: 12, borderWidth: 2, borderColor: '#E2E8F0', borderLeftWidth: 5, borderLeftColor: COLORS.primary },
  reportTitle: { fontSize: 14, fontWeight: '700', color: COLORS.textDark, flex: 1, marginRight: 10 },
  reportScore: { fontSize: 15, fontWeight: '900', color: COLORS.primary },
  seeMoreButton: { backgroundColor: COLORS.primary, padding: 12, borderRadius: 12, alignItems: 'center', marginTop: 8, borderWidth: 2, borderColor: COLORS.border, shadowColor: COLORS.black, shadowOffset: { width: 2, height: 2 }, shadowOpacity: 1, shadowRadius: 0, elevation: 2 },
  seeMoreButtonText: { color: COLORS.textWhite, fontWeight: '800', fontSize: 14 },
  // TIMETABLE
  timetableContainer: { backgroundColor: COLORS.cardBg, borderRadius: 20, padding: 20, marginBottom: 16, borderWidth: 2, borderColor: COLORS.border, shadowColor: COLORS.black, shadowOffset: { width: 4, height: 4 }, shadowOpacity: 1, shadowRadius: 0, elevation: 4 },
  timetableTitle: { fontSize: 20, fontWeight: '900', color: COLORS.textDark },
  timetableItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.itemBg, borderRadius: 12, marginBottom: 10, borderWidth: 2, borderColor: '#E2E8F0', overflow: 'hidden' },
  timeStrip: { backgroundColor: COLORS.primary, padding: 14, minWidth: 70, alignItems: 'center', justifyContent: 'center' },
  subjectTime: { color: '#FFFFFF', fontSize: 16, fontWeight: '900' },
  subjectAmPm: { color: 'rgba(255,255,255,0.8)', fontSize: 11, fontWeight: '600' },
  subjectContent: { flex: 1, paddingHorizontal: 14 },
  subjectName: { fontSize: 15, fontWeight: '700', color: COLORS.textDark },
  noTimetableData: { textAlign: 'center', color: COLORS.textLight, fontStyle: 'italic', marginVertical: 10 },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  editIconBtn: { padding: 8, backgroundColor: '#F3F4F6', borderRadius: 10, borderWidth: 2, borderColor: COLORS.border },
  // TIMETABLE EDITOR
  editorRow: { marginBottom: 20, backgroundColor: '#F9FAFB', padding: 12, borderRadius: 12, borderWidth: 1, borderColor: '#E2E8F0' },
  rowLabel: { fontSize: 12, color: '#888', fontWeight: '700', marginBottom: 5, textTransform: 'uppercase' },
  timeRangeContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  timeBox: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 8, padding: 8, width: '42%', alignItems: 'center' },
  timeLabel: { fontSize: 10, color: '#A0AEC0', fontWeight: 'bold', marginBottom: 2 },
  timeValue: { fontSize: 15, fontWeight: 'bold', color: '#864AF9' },
  pickerWrapper: { borderWidth: 2, borderColor: '#E2E8F0', borderRadius: 10, overflow: 'hidden', backgroundColor: '#fff' },
  picker: { height: 50, color: '#000' },
  buttonRow: { flexDirection: 'row', gap: 12, marginTop: 16 },
  actionBtn: { flex: 1, paddingVertical: 12, borderRadius: 12, alignItems: 'center', borderWidth: 2, borderColor: COLORS.border, shadowColor: COLORS.black, shadowOffset: { width: 2, height: 2 }, shadowOpacity: 1, shadowRadius: 0 },
  resetBtn: { backgroundColor: '#FFF' },
  saveBtn: { backgroundColor: COLORS.primary },
  resetBtnText: { color: '#000', fontWeight: '900', fontSize: 14 },
  saveBtnText: { color: '#FFF', fontWeight: '900', fontSize: 14 },
  closeModalBtn: { marginTop: 12, padding: 12, alignItems: 'center' },
  closeModalText: { color: COLORS.textLight, fontWeight: '700', fontSize: 14 },
  closePickerBtn: { marginTop: 10, backgroundColor: COLORS.primary, padding: 12, borderRadius: 10, alignItems: 'center' },
  // LEADERBOARD
  leaderboardContainer: { backgroundColor: COLORS.cardBg, borderRadius: 20, padding: 20, marginBottom: 16, borderWidth: 2, borderColor: COLORS.border, shadowColor: COLORS.black, shadowOffset: { width: 4, height: 4 }, shadowOpacity: 1, shadowRadius: 0, elevation: 4 },
  leaderboardTitle: { fontSize: 20, fontWeight: '900', color: COLORS.textDark, marginBottom: 16 },
  leaderboardItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.itemBg, padding: 14, marginBottom: 10, borderRadius: 12, borderWidth: 2, borderColor: '#E2E8F0' },
  leaderboardRank: { fontSize: 18, fontWeight: '900', color: COLORS.primary, width: 36 },
  leaderboardName: { flex: 1, fontSize: 15, fontWeight: '700', color: COLORS.textDark },
  leaderboardScore: { fontSize: 15, fontWeight: '900', color: COLORS.textDark },
  noLeaderboardData: { textAlign: 'center', color: COLORS.textLight, fontStyle: 'italic' },
  // SUBJECTS
  subjectsContainer: { backgroundColor: COLORS.cardBg, borderRadius: 20, padding: 20, marginBottom: 16, borderWidth: 2, borderColor: COLORS.border, shadowColor: COLORS.black, shadowOffset: { width: 4, height: 4 }, shadowOpacity: 1, shadowRadius: 0, elevation: 4 },
  subjectsTitle: { fontSize: 20, fontWeight: '900', color: COLORS.textDark, marginBottom: 8 },
  subjectsDescription: { fontSize: 14, color: COLORS.textLight, marginBottom: 16, fontWeight: '600' },
  subjectsButton: { backgroundColor: COLORS.primary, padding: 16, borderRadius: 14, alignItems: 'center', borderWidth: 2, borderColor: COLORS.border, shadowColor: COLORS.black, shadowOffset: { width: 3, height: 3 }, shadowOpacity: 1, shadowRadius: 0, elevation: 3 },
  subjectsButtonText: { color: COLORS.textWhite, fontWeight: '900', fontSize: 15, textTransform: 'uppercase' },
  // PACKAGES
  packagesScroll: { padding: 16, paddingBottom: 80 },
  packageGrid: { gap: 16 },
  packageCard: { borderRadius: 20, padding: 20, borderWidth: 3, borderColor: COLORS.border, shadowColor: COLORS.black, shadowOffset: { width: 5, height: 5 }, shadowOpacity: 1, shadowRadius: 0, elevation: 5, position: 'relative', overflow: 'hidden' },
  packageTitle: { fontSize: 20, fontWeight: '900', color: '#1A1A1A', marginBottom: 6 },
  packageDesc: { fontSize: 14, color: '#444', fontWeight: '600', marginBottom: 12, lineHeight: 20 },
  infoBadge: { backgroundColor: 'rgba(0,0,0,0.08)', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20, alignSelf: 'flex-start' },
  infoBadgeText: { fontSize: 12, fontWeight: '700', color: '#333' },
  dashedDivider: { borderBottomWidth: 2, borderColor: 'rgba(0,0,0,0.15)', borderStyle: 'dashed', marginVertical: 16 },
  packageFooter: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  deleteBtn: { padding: 10, backgroundColor: 'rgba(255,255,255,0.6)', borderRadius: 12, borderWidth: 2, borderColor: COLORS.border },
  downloadFullBtn: { flex: 1, backgroundColor: '#FFFFFF', paddingVertical: 14, paddingHorizontal: 16, borderRadius: 14, alignItems: 'center', borderWidth: 3, borderColor: COLORS.border, shadowColor: COLORS.black, shadowOffset: { width: 3, height: 3 }, shadowOpacity: 1, shadowRadius: 0 },
  downloadingBtn: { backgroundColor: '#FFF9C4' },
  downloadedBtn: { backgroundColor: '#DCFCE7' },
  downloadBtnText: { fontSize: 13, fontWeight: '900', color: '#1A1A1A', letterSpacing: 0.5 },
  cardCorner: { position: 'absolute', bottom: -15, right: -15, width: 60, height: 60, borderRadius: 30, backgroundColor: 'rgba(255,255,255,0.2)', borderWidth: 3, borderColor: 'rgba(0,0,0,0.1)' },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 40 },
  loadingText: { marginTop: 12, fontSize: 16, color: COLORS.textLight, fontWeight: '600' },
  // MODAL
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { width: '90%', backgroundColor: '#fff', borderRadius: 20, padding: 24, borderWidth: 3, borderColor: '#000', shadowColor: '#000', shadowOffset: { width: 6, height: 6 }, shadowOpacity: 1, shadowRadius: 0, elevation: 10 },
  modalTitle: { fontSize: 22, fontWeight: '900', color: '#000', marginBottom: 16, textAlign: 'center' },
  modalAvatar: { width: 100, height: 100, borderRadius: 50, borderWidth: 3, borderColor: COLORS.primary, alignSelf: 'center' },
  avatarBadge: { position: 'absolute', bottom: 0, right: 0, backgroundColor: COLORS.primary, borderRadius: 12, padding: 4, borderWidth: 2, borderColor: '#fff' },
  uploadOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', borderRadius: 50, justifyContent: 'center', alignItems: 'center' },
  // PROFILE INPUTS
  inputGroup: { marginBottom: 4 },
  modalLabel: { fontSize: 13, fontWeight: '700', color: '#555', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 },
  inputContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F7F9FC', borderRadius: 12, borderWidth: 2, borderColor: '#E2E8F0', paddingHorizontal: 14, paddingVertical: 4 },
  inputContainerActive: { backgroundColor: '#FFFFFF', borderColor: '#864AF9' },
  modalInput: { flex: 1, fontSize: 16, color: '#000', fontWeight: '600' },
  editIcon: { padding: 4, backgroundColor: '#E2E8F0', borderRadius: 6, marginLeft: 8, borderWidth: 1, borderColor: '#000' },
  // BUTTONS
  logoutBtn: { flex: 1, backgroundColor: '#FF4757', paddingVertical: 14, borderRadius: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#000', shadowColor: '#000', shadowOffset: { width: 2, height: 2 }, shadowOpacity: 1, shadowRadius: 0, elevation: 4 },
  cancelBtn: { flex: 1, backgroundColor: '#fff', paddingVertical: 14, borderRadius: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#000', shadowColor: '#000', shadowOffset: { width: 2, height: 2 }, shadowOpacity: 1, shadowRadius: 0, elevation: 4 },
  cancelReportBtn: { backgroundColor: '#fff', paddingVertical: 14, borderRadius: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#000', marginTop: 10, shadowColor: '#000', shadowOffset: { width: 2, height: 2 }, shadowOpacity: 1, shadowRadius: 0 },
  logoutText: { color: '#FFFFFF', fontWeight: '900', fontSize: 14, letterSpacing: 0.5 },
  cancelText: { color: '#000', fontWeight: '900', fontSize: 14, letterSpacing: 0.5 },
  cancelReportText: { color: '#000', fontWeight: '900', fontSize: 16, textTransform: 'uppercase' },
  // REPORTS MODAL
  tabContainer: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20, backgroundColor: COLORS.itemBg, borderRadius: 12, padding: 4, borderWidth: 2, borderColor: COLORS.border },
  tab: { flex: 1, alignItems: 'center', paddingVertical: 10, borderRadius: 8, marginHorizontal: 2, borderWidth: 2, borderColor: 'transparent' },
  activeTab: { backgroundColor: COLORS.primary, borderColor: COLORS.border, shadowColor: COLORS.black, shadowOffset: { width: 2, height: 2 }, shadowOpacity: 1, shadowRadius: 0, elevation: 2 },
  tabText: { fontSize: 13, color: COLORS.textLight, fontWeight: '700', textTransform: 'uppercase' },
  activeTabText: { color: COLORS.textWhite, fontWeight: '900' },
  modalReportList: { marginTop: 8, marginBottom: 20, maxHeight: 400 },
  modalReportItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: COLORS.itemBg, padding: 16, marginBottom: 12, borderRadius: 12, borderWidth: 2, borderColor: COLORS.border, borderLeftWidth: 6, borderLeftColor: COLORS.primary },
  modalReportTitle: { fontSize: 15, fontWeight: '700', color: COLORS.textDark, flex: 1, marginRight: 10 },
  modalReportScore: { fontSize: 16, color: COLORS.primary, fontWeight: '900' },
  // DELETE PACK MODAL
  modalContainer: { width: '85%', backgroundColor: '#fff', borderRadius: 20, padding: 24, borderWidth: 3, borderColor: '#000', shadowColor: '#000', shadowOffset: { width: 6, height: 6 }, shadowOpacity: 1, shadowRadius: 0, elevation: 10, alignItems: 'center' },
  trashIconContainer: { marginBottom: 16, backgroundColor: '#FFE5E5', width: 80, height: 80, borderRadius: 40, justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: '#000' },
  modalBtnRow: { width: '100%', flexDirection: 'row', gap: 12 },
  modalBtn: { flex: 1, paddingVertical: 14, borderRadius: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#000', shadowColor: '#000', shadowOffset: { width: 2, height: 2 }, shadowOpacity: 1, shadowRadius: 0 },
  modalBtnDestructive: { backgroundColor: '#FF3B30' },
  modalBtnGhost: { backgroundColor: '#FFF' },
  modalBtnTextRed: { color: '#FFF', fontWeight: '900', fontSize: 14 },
  modalBtnTextBlack: { color: '#000', fontWeight: '900', fontSize: 14 },
  modalMessage: { fontSize: 16, color: '#555', textAlign: 'center', marginBottom: 24, lineHeight: 22 },
  // SOUND PAGE
  SoundTitle: { fontSize: 32, fontWeight: '900', color: '#864AF9', marginBottom: 8, letterSpacing: 1, textTransform: 'uppercase' },
  SoundDescription: { fontSize: 16, color: '#2D3748', fontWeight: '600', marginBottom: 10, lineHeight: 22 },
});

export default styles;
