import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: '#F0F4FF' },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  loadingText: { marginTop: 10, fontSize: 16, color: '#555' },
  header: { backgroundColor: '#fff', paddingBottom: 8, elevation: 3, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  headerTop: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', paddingHorizontal: 16, paddingTop: 8 },
  questionCounter: { backgroundColor: '#864AF9', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 4, marginRight: 'auto' },
  counterText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  timerContainer: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 4 },
  timerIcon: { fontSize: 14 },
  timerText: { fontSize: 15, fontWeight: '700', color: '#333' },
  progressBarContainer: { height: 4, backgroundColor: '#E5E7EB', marginTop: 8 },
  progressBar: { height: '100%', backgroundColor: '#864AF9', borderRadius: 4 },
  scrollContent: { flexGrow: 1, paddingHorizontal: 16, paddingTop: 16, paddingBottom: 32 },
  questionWrapper: { flex: 1 },
  passageButton: { backgroundColor: '#EEF2FF', borderWidth: 1, borderColor: '#864AF9', borderRadius: 10, paddingVertical: 10, paddingHorizontal: 16, marginBottom: 12, alignSelf: 'flex-start' },
  passageButtonText: { color: '#864AF9', fontWeight: '700', fontSize: 13 },
  captionContainer: { flexDirection: 'row', backgroundColor: '#FFFBEB', borderWidth: 1, borderColor: '#FCD34D', borderRadius: 10, padding: 12, marginTop: 12 },
  captionIcon: { marginRight: 8 },
  captionIconText: { fontSize: 18 },
  captionContent: { flex: 1 },
  captionText: { fontSize: 13, color: '#92400E', fontWeight: '500' },
  reportContainer: { alignItems: 'flex-end', marginTop: 8 },
  reportButton: { flexDirection: 'row', alignItems: 'center', gap: 4, padding: 6 },
  reportText: { color: '#FF4444', fontSize: 12, fontWeight: '600' },
  submitButton: { backgroundColor: '#864AF9', borderRadius: 14, paddingVertical: 16, alignItems: 'center', marginTop: 20, elevation: 4, shadowColor: '#864AF9', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8 },
  submitButtonText: { color: '#fff', fontSize: 16, fontWeight: '800', letterSpacing: 0.5 },
  afterSubmitContainer: { marginTop: 16 },
  narrationToggle: { backgroundColor: '#F3F4F6', borderRadius: 10, paddingVertical: 12, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center' },
  narrationToggleText: { color: '#374151', fontWeight: '700', fontSize: 14 },
  narrationContainer: { marginTop: 8, backgroundColor: '#FAFAFA', borderRadius: 12, borderWidth: 1, borderColor: '#E5E7EB' },
  narrationScroll: { maxHeight: 220, padding: 14 },
  narrationTextWrapper: { marginBottom: 8 },
  narrationText: { fontSize: 14, color: '#374151', lineHeight: 22 },
  narrationImage: { width: '100%', height: 200, borderRadius: 10, marginVertical: 8, resizeMode: 'contain' },
  narrationVideo: { width: '100%', height: 200, borderRadius: 10, marginVertical: 8 },
  nextButton: { backgroundColor: '#10B981', borderRadius: 14, paddingVertical: 16, alignItems: 'center', marginTop: 12, elevation: 4 },
  nextButtonText: { color: '#fff', fontSize: 16, fontWeight: '800' },
  noQuestionsText: { textAlign: 'center', marginTop: 60, color: '#999', fontSize: 16 },
  bottomStrip: { backgroundColor: '#fff', borderTopWidth: 1, borderColor: '#E5E7EB', paddingVertical: 8 },
  // Breadcrumb
   breadcrumbContainer: {
    marginBottom: 12,
    height: 40, // Give it a fixed height to prevent layout jumps
  },
  breadcrumbScroll: {
    flexDirection: "row",
    alignItems: "center",
    paddingRight: 20, // IMPT: Adds space at the end so you can read the last item
    flexGrow: 1,
  },
  breadcrumbItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F7F9FC",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    maxWidth: 150,
  },
  breadcrumbIcon: { fontSize: 14, marginRight: 6 },
  breadcrumbText: { fontSize: 13, fontWeight: "600", color: "#4A5568" },
  breadcrumbSeparator: {
    fontSize: 18,
    color: "#CBD5E0",
    marginHorizontal: 8,
    fontWeight: "300",
  },
  // Passage Modal
  passageModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  passageModalContent: { backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: '80%', paddingBottom: 32 },
  passageModalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderBottomWidth: 1, borderColor: '#E5E7EB' },
  passageModalTitle: { fontSize: 18, fontWeight: '800', color: '#111' },
  passageCloseButton: { backgroundColor: '#F3F4F6', borderRadius: 20, width: 32, height: 32, justifyContent: 'center', alignItems: 'center' },
  passageCloseButtonText: { fontSize: 16, color: '#374151' },
  passageModalBody: { padding: 20 },
  passageText: { fontSize: 15, color: '#374151', lineHeight: 24 },
  // Results Modal
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { backgroundColor: '#fff', borderRadius: 24, padding: 28, width: '88%', alignItems: 'center', borderWidth: 3, borderColor: '#000', shadowColor: '#000', shadowOffset: { width: 6, height: 6 }, shadowOpacity: 1, shadowRadius: 0 },
  stickerImage: { width: 100, height: 100, marginBottom: 12 },
  resultTitle: { fontSize: 22, fontWeight: '900', color: '#111', marginBottom: 12 },
  scoreContainer: { backgroundColor: '#F9FAFB', borderRadius: 16, padding: 16, width: '100%', alignItems: 'center', borderWidth: 2, borderColor: '#E5E7EB', marginBottom: 20 },
  resultText: { fontSize: 15, color: '#374151', fontWeight: '600' },
  divider: { height: 1, backgroundColor: '#E5E7EB', width: '80%', marginVertical: 10 },
  resultPercentage: { fontSize: 40, fontWeight: '900', color: '#864AF9' },
  modalButton: { backgroundColor: '#864AF9', borderRadius: 14, paddingVertical: 14, paddingHorizontal: 24, alignItems: 'center', width: '100%', borderWidth: 2, borderColor: '#000', shadowColor: '#000', shadowOffset: { width: 3, height: 3 }, shadowOpacity: 1, shadowRadius: 0 },
  modalButtonText: { color: '#fff', fontWeight: '900', fontSize: 15, textTransform: 'uppercase', letterSpacing: 0.5 },
  // Report Modal
  reportModalContent: { backgroundColor: '#fff', borderRadius: 20, margin: 20, padding: 24, borderWidth: 2, borderColor: '#000' },
  modalHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  reportModalTitle: { fontSize: 18, fontWeight: '800', color: '#111' },
  reportModalSubtitle: { fontSize: 14, color: '#555', marginBottom: 12, fontWeight: '500' },
  reportInput: { borderWidth: 2, borderColor: '#E5E7EB', borderRadius: 12, padding: 12, fontSize: 14, color: '#111', minHeight: 100, textAlignVertical: 'top' },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 16 },
  reportModalBtn: { flex: 1, paddingVertical: 12, borderRadius: 10, alignItems: 'center', borderWidth: 2, borderColor: '#000' },
  cancelBtn: { backgroundColor: '#F3F4F6' },
  submitReportBtn: { backgroundColor: '#864AF9' },
  cancelBtnText: { fontWeight: '700', color: '#374151' },
  submitBtnText: { fontWeight: '700', color: '#fff' },
  // Exit Modal
  exitOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'center', alignItems: 'center' },
  exitContainer: { width: '85%', backgroundColor: '#fff', borderRadius: 24, padding: 24, borderWidth: 3, borderColor: '#000', shadowColor: '#000', shadowOffset: { width: 8, height: 8 }, shadowOpacity: 1, shadowRadius: 0, elevation: 10, alignItems: 'center' },
  exitHeader: { marginBottom: 16, backgroundColor: '#FFE5E5', width: 80, height: 80, borderRadius: 40, justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: '#000' },
  exitTitle: { fontSize: 24, fontWeight: '900', color: '#000', marginBottom: 8, textAlign: 'center', textTransform: 'uppercase' },
  exitMessage: { fontSize: 15, color: '#555', textAlign: 'center', marginBottom: 24, fontWeight: '600', lineHeight: 22 },
  exitButtonColumn: { width: '100%', gap: 12 },
  exitBtn: { width: '100%', paddingVertical: 14, borderRadius: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#000', shadowColor: '#000', shadowOffset: { width: 3, height: 3 }, shadowOpacity: 1, shadowRadius: 0 },
  exitBtnPrimary: { backgroundColor: '#864AF9' },
  exitBtnDestructive: { backgroundColor: '#FFCCCC' },
  exitBtnGhost: { backgroundColor: '#FFF', borderWidth: 2, borderColor: 'transparent', elevation: 0, shadowOpacity: 0 },
  exitBtnTextWhite: { color: '#FFF', fontWeight: '900', fontSize: 16, textTransform: 'uppercase' },
  exitBtnTextRed: { color: '#D00000', fontWeight: '900', fontSize: 15, textTransform: 'uppercase' },
  exitBtnTextBlack: { color: '#777', fontWeight: '700', fontSize: 14, textDecorationLine: 'underline' },
  // Thanks / Upsell Modal
  iconContainer: { backgroundColor: '#55E6C1', width: 80, height: 80, borderRadius: 40, borderWidth: 3, borderColor: '#000', justifyContent: 'center', alignItems: 'center', marginBottom: 20, marginTop: -60 },
  thanksText: { fontSize: 24, fontWeight: '900', color: '#000', textAlign: 'center', textTransform: 'uppercase', marginBottom: 10 },
  subText: { fontSize: 16, fontWeight: '600', color: '#000', textAlign: 'center', marginBottom: 25 },
  upsellBox: { backgroundColor: '#FBBF24', borderWidth: 3, borderColor: '#000000', borderRadius: 12, padding: 15, marginVertical: 15, width: '100%', shadowColor: '#000', shadowOffset: { width: 4, height: 4 }, shadowOpacity: 1, shadowRadius: 0, elevation: 5 },
  upsellTitle: { fontSize: 18, fontWeight: '900', color: '#000000', textTransform: 'uppercase', marginBottom: 10, textAlign: 'center' },
  upsellList: { marginBottom: 15 },
  upsellItem: { fontSize: 14, fontWeight: '700', color: '#2D3748', marginBottom: 6 },
  upgradeBtn: { backgroundColor: '#864AF9', borderWidth: 2, borderColor: '#000000', paddingVertical: 12, borderRadius: 8, alignItems: 'center' },
  upgradeBtnText: { color: '#FFFFFF', fontWeight: '900', fontSize: 16, letterSpacing: 1 },
  // Rough Sheet
  rsContainer: { flex: 1, backgroundColor: '#fff' },
  rsHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderColor: '#eee', backgroundColor: '#f9f9f9' },
  rsTitle: { fontSize: 18, fontWeight: 'bold', color: '#333' },
  rsControls: { flexDirection: 'row', gap: 10 },
  rsBtnClear: { paddingVertical: 8, paddingHorizontal: 15, borderRadius: 20, backgroundColor: '#eee' },
  rsBtnClose: { paddingVertical: 8, paddingHorizontal: 15, borderRadius: 20, backgroundColor: '#000' },
  rsBtnText: { fontWeight: 'bold', fontSize: 14 },
  rsCanvas: { flex: 1, backgroundColor: '#ffffff' },
  // Calculator
  calcOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center' },
  calcContainer: { width: '85%', backgroundColor: '#fff', borderRadius: 20, padding: 20, borderWidth: 3, borderColor: '#000', shadowColor: '#000', shadowOffset: { width: 6, height: 6 }, shadowOpacity: 1, shadowRadius: 0, elevation: 10 },
  calcDisplay: { backgroundColor: '#222', padding: 20, borderRadius: 12, marginBottom: 20, alignItems: 'flex-end', borderWidth: 2, borderColor: '#000' },
  calcDisplayText: { color: '#0F0', fontSize: 32, fontWeight: 'bold', fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace' },
  calcKeypad: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 10 },
  calcBtn: { width: '22%', aspectRatio: 1, backgroundColor: '#eee', justifyContent: 'center', alignItems: 'center', borderRadius: 10, borderWidth: 2, borderColor: '#000', shadowColor: '#000', shadowOffset: { width: 2, height: 2 }, shadowOpacity: 1, shadowRadius: 0 },
  calcBtnPurple: { backgroundColor: '#864AF9' },
  calcBtnRed: { backgroundColor: '#ffcccc' },
  calcBtnText: { fontSize: 22, fontWeight: 'bold', color: '#000' },
  calcCloseBtn: { marginTop: 20, backgroundColor: '#000', padding: 12, borderRadius: 10, alignItems: 'center' },
  calcCloseText: { color: '#fff', fontWeight: 'bold', letterSpacing: 1 },
  // Labels
  label: { fontSize: 16, color: '#1F2937', lineHeight: 24 },
});

export default styles;
