/**
 * SmartMath.js
 *
 * Renders LaTeX via KaTeX entirely offline.
 *
 * HOW THE OFFLINE TRICK WORKS:
 * Instead of loading KaTeX from a CDN (which fails offline), we ship the
 * katex JS and CSS as plain text strings inside the app bundle and inject
 * them directly into the WebView HTML. No network request is ever made.
 *
 * SETUP (one-time):
 *   1. npm install katex
 *   2. Run the setup script once to generate katexAssets.js:
 *        node scripts/bundleKatex.js
 *   3. Commit katexAssets.js — it never changes unless you upgrade katex.
 *
 * If katexAssets.js does not exist yet, this component falls back to the
 * CDN so the app still works while you run the setup.
 */

import React, { useState } from 'react';
import { View } from 'react-native';
import { WebView } from 'react-native-webview';

// ─── Load pre-bundled KaTeX assets ───────────────────────────────────────────
// This file is generated by scripts/bundleKatex.js.
// If it doesn't exist yet, the catch will fall back to CDN mode.
let KATEX_JS = null;
let KATEX_CSS = null;

try {
  const assets = require('./katexAssets');
  KATEX_JS  = assets.KATEX_JS;
  KATEX_CSS = assets.KATEX_CSS;
} catch (e) {
  // katexAssets.js not generated yet — will use CDN as fallback
  console.warn('[SmartMath] katexAssets.js not found. Run: node scripts/bundleKatex.js');
}

// ─── Build the HTML string once (not inside render) ──────────────────────────
const buildHtml = (latex, inline, isReady) => {
  // Escape backslashes for injection into the JS string literal
  const safeTex = latex.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

  // If assets are bundled, inject them inline. Otherwise fall back to CDN.
  const head = KATEX_JS
    ? `<style>${KATEX_CSS}</style><script>${KATEX_JS}</script>`
    : `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css">
       <script src="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js"></script>`;

  return `<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    ${head}
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body {
        background: transparent;
        display: inline-block;
        overflow: hidden;
        white-space: nowrap;
        opacity: ${isReady ? 1 : 0};
      }
      #m { display: inline-block; font-size: 15px; padding: 4px 8px; color: black; }
    </style>
  </head>
  <body>
    <div id="m"></div>
    <script>
      function measure() {
        var el = document.getElementById('m');
        var h = el.offsetHeight;
        var w = el.offsetWidth;
        if (h > 0 && w > 0) {
          window.ReactNativeWebView.postMessage(JSON.stringify({ height: h, width: w }));
        }
      }
      try {
        var el = document.getElementById('m');
        katex.render("${safeTex}", el, { displayMode: ${!inline}, throwOnError: false });
        setTimeout(measure, 100);
        setTimeout(measure, 500);
      } catch(e) {
        window.ReactNativeWebView.postMessage(JSON.stringify({ error: e.message }));
      }
    </script>
  </body>
</html>`;
};

// ─── Component ────────────────────────────────────────────────────────────────
const SmartMath = ({ latex, inline = true }) => {
  const [dims, setDims] = useState({ h: 30, w: 60 });
  const [isReady, setIsReady] = useState(false);

  const html = buildHtml(latex, inline, isReady);

  return (
    <View
      style={{
        height: dims.h,
        width: inline ? dims.w : '100%',
        marginHorizontal: 2,
        opacity: isReady ? 1 : 0,
      }}
    >
      <WebView
        key={latex}
        originWhitelist={['*']}
        source={{ html }}
        scrollEnabled={false}
        onMessage={(e) => {
          try {
            const data = JSON.parse(e.nativeEvent.data);
            if (data.height && data.width) {
              setDims({ h: data.height + 6, w: data.width + 8 });
              setIsReady(true);
            }
          } catch (err) {
            // malformed message — ignore
          }
        }}
        style={{ backgroundColor: 'transparent' }}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        // Critical: allow inline HTML content (no network needed when bundled)
        mixedContentMode="always"
        allowFileAccess={true}
      />
    </View>
  );
};

export default SmartMath;
