import React, { useState, useRef, useEffect } from "react";
import {
  View,
  Text,
  Image,
  TextInput,
  StyleSheet,
  TouchableOpacity,
  Animated,
  Dimensions,
} from "react-native";
import { WebView } from "react-native-webview";
import * as FileSystem from 'expo-file-system/legacy';

const { width: SCREEN_WIDTH } = Dimensions.get("window");

// ─── Load pre-bundled KaTeX (offline-safe) ────────────────────────────────────
// Generated by: node scripts/bundleKatex.js
// Falls back to CDN if the file hasn't been generated yet.
let KATEX_JS  = null;
let KATEX_CSS = null;
try {
  const assets = require('../screens/QuestionScreen/katexAssets');
  KATEX_JS  = assets.KATEX_JS;
  KATEX_CSS = assets.KATEX_CSS;
} catch (e) {
  console.warn('[QuestionRenderer] katexAssets.js not found — using CDN fallback. Run: node scripts/bundleKatex.js');
}

const katexHead = KATEX_JS
  ? `<style>${KATEX_CSS}</style><script>${KATEX_JS}</script>`
  : `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css">
     <script src="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js"></script>`;

// ─── Offline image directory (must match useQuestionData.js) ──────────────────
const OFFLINE_IMAGE_DIR = FileSystem.documentDirectory + 'offline_images/';

// ─── Unicode helper ───────────────────────────────────────────────────────────
const fixUnicode = (str) => {
  if (!str || typeof str !== 'string') return str || "";
  let decoded = str.replace(/\\u([0-9a-fA-F]{4})/gi, (match, grp) =>
    String.fromCharCode(parseInt(grp, 16))
  );
  decoded = decoded.replace("$$\\mathbb{N}$$", "₦");
  return decoded;
};

// ─── Image URI resolver ───────────────────────────────────────────────────────
// When offline, swap remote URLs for local file paths.
// The filename must match what was used when the image was downloaded.
const resolveImageUri = (uri, isOffline) => {
  if (!uri) return uri;
  if (!isOffline) return uri;
  // If it's already a local file path, leave it alone
  if (uri.startsWith('file://') || uri.startsWith(FileSystem.documentDirectory)) return uri;
  // Build the local path the same way useQuestionData does
  const safeFilename = encodeURIComponent(uri);
  return OFFLINE_IMAGE_DIR + safeFilename;
};

// ─── SmartMath ────────────────────────────────────────────────────────────────
const SmartMath = ({ latex, inline = true }) => {
  const [dims, setDims] = useState({ h: 30, w: 60 });
  const [isReady, setIsReady] = useState(false);

  const cleanLatex = fixUnicode(latex);
  const safeTex = cleanLatex.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

  const html = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    ${katexHead}
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body {
        background: transparent;
        display: inline-block;
        overflow: hidden;
        white-space: nowrap;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        opacity: ${isReady ? 1 : 0};
      }
      #m { display: inline-block; font-size: 15px; padding: 4px 8px; color: black; }
    </style>
  </head>
  <body>
    <div id="m"></div>
    <script>
      function measure() {
        var el = document.getElementById('m');
        var h = el.offsetHeight;
        var w = el.offsetWidth;
        if (h > 0 && w > 0) {
          window.ReactNativeWebView.postMessage(JSON.stringify({ height: h, width: w }));
        }
      }
      try {
        katex.render("${safeTex}", document.getElementById('m'), {
          displayMode: ${!inline},
          throwOnError: false
        });
        setTimeout(measure, 100);
        setTimeout(measure, 500);
      } catch(e) {
        window.ReactNativeWebView.postMessage(JSON.stringify({ error: e.message }));
      }
    </script>
  </body>
</html>`;

  return (
    <View style={{ height: dims.h, width: inline ? dims.w : '100%', marginHorizontal: 2, opacity: isReady ? 1 : 0 }}>
      <WebView
        key={cleanLatex}
        originWhitelist={['*']}
        source={{ html }}
        scrollEnabled={false}
        onMessage={(e) => {
          try {
            const data = JSON.parse(e.nativeEvent.data);
            if (data.height && data.width) {
              setDims({ h: data.height + 6, w: data.width + 8 });
              setIsReady(true);
            }
          } catch (err) {}
        }}
        style={{ backgroundColor: 'transparent' }}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        mixedContentMode="always"
        allowFileAccess={true}
      />
    </View>
  );
};

// ─── SmartHtml (tables) ───────────────────────────────────────────────────────
const SmartHtml = ({ htmlContent }) => {
  const [height, setHeight] = useState(40);
  const [isReady, setIsReady] = useState(false);

  const html = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body {
        background: transparent;
        overflow: hidden;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        opacity: ${isReady ? 1 : 0};
      }
      table { width: 100%; border-collapse: collapse; font-size: 14px; }
      th, td { border: 1px solid #ccc; padding: 8px; text-align: left; color: #333; }
      th { background-color: #f2f2f2; font-weight: bold; }
    </style>
  </head>
  <body>
    <div id="wrapper">${htmlContent}</div>
    <script>
      function measure() {
        var h = document.getElementById('wrapper').offsetHeight;
        if (h > 0) window.ReactNativeWebView.postMessage(JSON.stringify({ height: h }));
      }
      setTimeout(measure, 100);
      setTimeout(measure, 500);
      setTimeout(measure, 1000);
    </script>
  </body>
</html>`;

  return (
    <View style={{ height, width: '100%', marginVertical: 10, opacity: isReady ? 1 : 0 }}>
      <WebView
        originWhitelist={['*']}
        source={{ html }}
        scrollEnabled={false}
        onMessage={(e) => {
          try {
            const data = JSON.parse(e.nativeEvent.data);
            if (data.height) { setHeight(data.height + 10); setIsReady(true); }
          } catch (err) {}
        }}
        style={{ backgroundColor: 'transparent' }}
        javaScriptEnabled={true}
        mixedContentMode="always"
        allowFileAccess={true}
      />
    </View>
  );
};

// ─── Content renderer ─────────────────────────────────────────────────────────
const renderContentWithMath = (rawContent, textStyle = {}) => {
  if (!rawContent) return null;
  const content = fixUnicode(rawContent);
  const parts = content.split(/(\$\$[\s\S]*?\$\$|\$[^\$\n]+?\$|<table[\s\S]*?<\/table>)/g);

  return (
    <View style={{ flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center' }}>
      {parts.map((part, index) => {
        if (part.startsWith('$$') && part.endsWith('$$')) {
          return <SmartMath key={`math-block-${index}`} latex={part.slice(2, -2).trim()} inline={false} />;
        }
        if (part.startsWith('$') && part.endsWith('$') && !part.startsWith('$$')) {
          return <SmartMath key={`math-inline-${index}`} latex={part.slice(1, -1).trim()} inline={true} />;
        }
        if (part.startsWith('<table') && part.endsWith('</table>')) {
          return <View key={`table-${index}`} style={{ width: '100%' }}><SmartHtml htmlContent={part} /></View>;
        }
        if (part) {
          const fragments = part.split(/(\*\*.*?\*\*|__.*?__|\{(#[0-9a-fA-F]{3,6}|[a-z]+)\}.*?\{\/\})/g);
          return fragments.map((sub, subIndex) => {
            const key = `text-${index}-${subIndex}`;
            if (!sub || sub === 'undefined') return null;
            if (sub.startsWith('**') && sub.endsWith('**')) {
              return <Text key={key} style={[styles.label, textStyle, { fontWeight: 'bold' }]} selectable={false}>{sub.slice(2, -2)}</Text>;
            }
            if (sub.startsWith('__') && sub.endsWith('__')) {
              return <Text key={key} style={[styles.label, textStyle, { textDecorationLine: 'underline' }]} selectable={false}>{sub.slice(2, -2)}</Text>;
            }
            if (sub.match(/^\{(#[0-9a-fA-F]{3,6}|[a-z]+)\}.*\{\/\}$/)) {
              const colorMatch = sub.match(/^\{(#[0-9a-fA-F]{3,6}|[a-z]+)\}(.*)\{\/\}$/);
              return <Text key={key} style={[styles.label, textStyle, { color: colorMatch[1] }]} selectable={false}>{colorMatch[2]}</Text>;
            }
            return <Text key={key} style={[styles.label, textStyle]} selectable={false}>{sub}</Text>;
          });
        }
        return null;
      })}
    </View>
  );
};

// ─── AnimatedOption ───────────────────────────────────────────────────────────
const AnimatedOption = ({ option, isSelected, onPress, isCorrect, isSubmitted }) => {
  const scaleAnim    = useRef(new Animated.Value(1)).current;
  const selectedAnim = useRef(new Animated.Value(isSelected ? 1 : 0)).current;

  useEffect(() => {
    Animated.timing(selectedAnim, { toValue: isSelected ? 1 : 0, duration: 200, useNativeDriver: false }).start();
  }, [isSelected]);

  const finalBg  = selectedAnim.interpolate({ inputRange: [0, 1], outputRange: ['#FFFFFF', '#F7F3FF'] });
  const finalBrd = selectedAnim.interpolate({ inputRange: [0, 1], outputRange: ['#E2E8F0', '#864AF9'] });

  let bg  = finalBg;
  let brd = finalBrd;
  if (isSubmitted) {
    bg  = isCorrect ? '#F0FFF4' : isSelected ? '#FFF5F5' : finalBg;
    brd = isCorrect ? '#48BB78' : isSelected ? '#F56565' : finalBrd;
  }

  return (
    <Animated.View style={{ transform: [{ scale: scaleAnim }], marginBottom: 12 }}>
      <TouchableOpacity
        onPress={onPress}
        disabled={isSubmitted}
        activeOpacity={1}
        onPressIn={() => Animated.spring(scaleAnim, { toValue: 0.97, useNativeDriver: true }).start()}
        onPressOut={() => Animated.spring(scaleAnim, { toValue: 1, useNativeDriver: true }).start()}
      >
        <Animated.View style={[styles.optionContainer, { backgroundColor: bg, borderColor: brd }]}>
          <View style={styles.radioContainer}>
            <View style={[
              styles.radioOuter,
              isSelected && styles.radioOuterSelected,
              isSubmitted && isCorrect && styles.radioOuterCorrect,
              isSubmitted && !isCorrect && isSelected && styles.radioOuterIncorrect,
            ]}>
              {isSelected && (
                <View style={[
                  styles.radioInner,
                  isSubmitted && isCorrect && styles.radioInnerCorrect,
                  isSubmitted && !isCorrect && isSelected && styles.radioInnerIncorrect,
                ]} />
              )}
            </View>
          </View>
          <View style={styles.optionTextContainer}>
            {renderContentWithMath(option, styles.optionText)}
          </View>
          {isSubmitted && isCorrect && <Text style={styles.correctIcon}>✓</Text>}
          {isSubmitted && !isCorrect && isSelected && <Text style={styles.incorrectIcon}>✗</Text>}
        </Animated.View>
      </TouchableOpacity>
    </Animated.View>
  );
};

// ─── Question type components ─────────────────────────────────────────────────
const ObjectiveQuestion = ({ question, selectedOption, onSelection, isSubmitted, isOffline }) => (
  <View style={styles.questionContainer}>
    {question.image && (
      <View style={styles.imageContainer}>
        <Image
          source={{ uri: resolveImageUri(question.image, isOffline) }}
          style={styles.questionImage}
          // Show a placeholder colour while loading
          defaultSource={require('../assets/education.png')}
        />
      </View>
    )}
    <View style={styles.questionTextContainer}>
      {renderContentWithMath(question.content, styles.questionText)}
    </View>
    <View style={styles.optionsWrapper}>
      {question.options.map((opt, i) => (
        <AnimatedOption
          key={i}
          option={opt}
          isSelected={selectedOption === opt}
          onPress={() => onSelection(opt)}
          isCorrect={isSubmitted ? opt === question.answer : null}
          isSubmitted={isSubmitted}
        />
      ))}
    </View>
  </View>
);

const TheoryQuestion = ({ question, onAnswerChange, value, isSubmitted, isOffline }) => {
  const [isFocused, setIsFocused] = useState(false);
  return (
    <View style={styles.questionContainer}>
      {question.image && (
        <View style={styles.imageContainer}>
          <Image source={{ uri: resolveImageUri(question.image, isOffline) }} style={styles.questionImage} />
        </View>
      )}
      <View style={styles.questionTextContainer}>
        {renderContentWithMath(question.content, styles.questionText)}
      </View>
      <TextInput
        style={[styles.textArea, isFocused && styles.textAreaFocused, isSubmitted && styles.textAreaSubmitted]}
        placeholder="Write your answer here..."
        multiline
        numberOfLines={6}
        onChangeText={onAnswerChange}
        value={value}
        onFocus={() => setIsFocused(true)}
        onBlur={() => setIsFocused(false)}
        editable={!isSubmitted}
      />
    </View>
  );
};

const FillInTheGapsQuestion = ({ question, onAnswerChange, value, isSubmitted, isOffline }) => {
  const [isFocused, setIsFocused] = useState(false);
  const isCorrect = value?.toLowerCase().trim() === question.answer?.toLowerCase().trim();

  return (
    <View style={styles.questionContainer}>
      {question.image && (
        <View style={styles.imageContainer}>
          <Image source={{ uri: resolveImageUri(question.image, isOffline) }} style={styles.questionImage} />
        </View>
      )}
      <View style={styles.questionTextContainer}>
        {renderContentWithMath(question.content, styles.questionText)}
      </View>
      <TextInput
        style={[
          styles.input,
          isFocused && styles.inputFocused,
          isSubmitted && (isCorrect
            ? { borderColor: '#48BB78', backgroundColor: '#F0FFF4' }
            : { borderColor: '#F56565', backgroundColor: '#FFF5F5' }),
        ]}
        placeholder="Type your answer..."
        onChangeText={onAnswerChange}
        value={value}
        onFocus={() => setIsFocused(true)}
        onBlur={() => setIsFocused(false)}
        editable={!isSubmitted}
      />
      {isSubmitted && !isCorrect && (
        <View style={{ marginTop: 8, padding: 8, backgroundColor: '#E6FFFA', borderRadius: 8 }}>
          <Text style={{ color: '#2C7A7B', fontWeight: 'bold' }}>
            Correct Answer: {fixUnicode(question.answer)}
          </Text>
        </View>
      )}
    </View>
  );
};

// ─── Main switch ──────────────────────────────────────────────────────────────
const QuestionRenderer = ({ question, onAnswerSelected, selectedAnswer, isSubmitted, isOffline = false }) => {
  const handleSelection    = (val) => !isSubmitted && onAnswerSelected(question.QuestionId, val);
  const handleAnswerChange = (val) => !isSubmitted && onAnswerSelected(question.QuestionId, val);

  switch (question.type) {
    case 'multiple_choice':
    case 'true_false':
      return <ObjectiveQuestion question={question} selectedOption={selectedAnswer} onSelection={handleSelection} isSubmitted={isSubmitted} isOffline={isOffline} />;
    case 'theory':
      return <TheoryQuestion question={question} onAnswerChange={handleAnswerChange} value={selectedAnswer || ''} isSubmitted={isSubmitted} isOffline={isOffline} />;
    case 'short_answer':
      return <FillInTheGapsQuestion question={question} onAnswerChange={handleAnswerChange} value={selectedAnswer || ''} isSubmitted={isSubmitted} isOffline={isOffline} />;
    default:
      return (
        <View style={styles.unsupportedContainer}>
          <Text style={styles.unsupportedText}>Unsupported: {question.type}</Text>
        </View>
      );
  }
};

// ─── Styles ───────────────────────────────────────────────────────────────────
const styles = StyleSheet.create({
  questionContainer: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 20, elevation: 4, marginBottom: 20 },
  imageContainer: { marginBottom: 20, borderRadius: 12, overflow: 'hidden' },
  questionImage: { width: '100%', height: 200, resizeMode: 'contain' },
  questionTextContainer: { marginBottom: 20 },
  questionText: { fontSize: 18, fontWeight: '600', color: '#2D3748' },
  optionsWrapper: { marginTop: 8 },
  optionContainer: { flexDirection: 'row', alignItems: 'center', padding: 16, borderRadius: 12, borderWidth: 2, minHeight: 60 },
  radioContainer: { marginRight: 12 },
  radioOuter: { width: 24, height: 24, borderRadius: 12, borderWidth: 2, borderColor: '#CBD5E0', justifyContent: 'center', alignItems: 'center' },
  radioOuterSelected: { borderColor: '#864AF9' },
  radioOuterCorrect: { borderColor: '#48BB78' },
  radioOuterIncorrect: { borderColor: '#F56565' },
  radioInner: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#864AF9' },
  radioInnerCorrect: { backgroundColor: '#48BB78' },
  radioInnerIncorrect: { backgroundColor: '#F56565' },
  optionTextContainer: { flex: 1 },
  optionText: { fontSize: 15, color: '#2D3748', lineHeight: 20 },
  label: { fontSize: 16, color: '#333' },
  correctIcon: { fontSize: 20, color: '#48BB78', marginLeft: 8 },
  incorrectIcon: { fontSize: 20, color: '#F56565', marginLeft: 8 },
  textArea: { borderWidth: 2, borderColor: '#E2E8F0', borderRadius: 12, padding: 15, textAlignVertical: 'top', minHeight: 120 },
  textAreaFocused: { borderColor: '#864AF9' },
  textAreaSubmitted: { backgroundColor: '#F7F9FC' },
  input: { borderWidth: 2, borderColor: '#E2E8F0', borderRadius: 12, padding: 15 },
  inputFocused: { borderColor: '#864AF9' },
  unsupportedContainer: { padding: 20, backgroundColor: '#FFF5F5' },
  unsupportedText: { color: '#C53030', textAlign: 'center' },
});

export default QuestionRenderer;