import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  decryptingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
  },
  decryptingText: {
    marginTop: 16,
    fontSize: 16,
    fontWeight: '700',
    color: '#2D3748',
  },
  container: { flex: 1, backgroundColor: '#F8F9FE', paddingHorizontal: 16, paddingTop: 16 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 16,
    elevation: 4,
  },
  subjectSelectionTitleWithButton: { fontSize: 20, fontWeight: '800', color: '#2D3748', flex: 1, marginRight: 12 },
  headerButton: { backgroundColor: '#864AF9', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 12 },
  headerButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
  subjectListWrapper: { justifyContent: 'space-between' },
  subjectItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    marginBottom: 16,
    elevation: 5,
    width: (width - 48) / 2,
    height: 160,
    borderWidth: 1,
    borderColor: 'rgba(134, 74, 249, 0.1)',
  },
  subCont: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 16 },
  subImg: { width: 50, height: 50, marginBottom: 12 },
  subjectText: { fontSize: 15, fontWeight: '700', color: '#2D3748', textAlign: 'center' },
  // Offline banners
  offlineBanner: {
    backgroundColor: '#EF4444',
    padding: 10,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    gap: 8,
  },
  offlineBannerText: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 13 },
  downloadIconBtn: { padding: 10, backgroundColor: '#F7F3FF', borderRadius: 12, borderWidth: 1, borderColor: '#864AF9' },
  savedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DEF7EC',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    marginTop: 8,
  },
  // Modal
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    minHeight: '60%',
    borderTopWidth: 4,
    borderColor: '#111827',
  },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  modalTitle: { fontSize: 24, fontWeight: '900', color: '#111827' },
  modalSub: { fontSize: 14, color: '#64748B', marginBottom: 20, fontWeight: '600' },
  modalSubjectCard: {
    flex: 1,
    backgroundColor: '#F3F4F6',
    padding: 16,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalSubjectCardActive: { backgroundColor: '#F7F3FF', borderColor: '#864AF9' },
  modalSubjectText: { fontWeight: '700', color: '#111827' },
  modalBtn: {
    backgroundColor: '#864AF9',
    padding: 18,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 16,
    borderWidth: 3,
    borderColor: '#111827',
    shadowColor: '#111827',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  modalBtnText: { color: '#FFFFFF', fontWeight: '900', fontSize: 16, textTransform: 'uppercase' },
  modalCenter: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  sizeText: { fontSize: 28, fontWeight: '900', color: '#111827', marginTop: 16 },
  progressBarBg: {
    width: '100%',
    height: 20,
    backgroundColor: '#E5E7EB',
    borderRadius: 10,
    marginTop: 20,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#111827',
  },
  progressBarFill: { height: '100%', backgroundColor: '#10B981' },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    marginTop: 4,
  },
  clearStorageBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF2F2',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FECACA',
    gap: 4,
  },
  clearStorageText: { color: '#EF4444', fontSize: 12, fontWeight: '700' },
  // School work sections
  schoolWorkSection: { marginBottom: 16 },
  sectionHeader: { marginBottom: 10 },
  sectionTitle: { fontSize: 16, fontWeight: '800', color: '#2D3748', marginBottom: 8 },
  districtSectionTitle: { color: '#6D28D9' },
  workCard: {
    backgroundColor: '#FFFFFF',
    padding: 14,
    borderRadius: 12,
    marginRight: 12,
    minWidth: 160,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    elevation: 2,
  },
  districtCardBorder: { borderLeftWidth: 4, borderLeftColor: '#6D28D9' },
  workTitle: { fontSize: 14, fontWeight: '700', color: '#2D3748' },
  // Paywall upsell
  premiumUpsellContainer: {
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 24,
  },
  lockCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#F3E8FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 3,
    borderColor: '#864AF9',
  },
  premiumUpsellTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#111827',
    marginBottom: 10,
    textAlign: 'center',
  },
  premiumUpsellText: {
    fontSize: 15,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
    fontWeight: '600',
  },
  upsellBtn: {
    backgroundColor: '#864AF9',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 16,
    borderWidth: 3,
    borderColor: '#111827',
    shadowColor: '#111827',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    marginBottom: 16,
  },
  upsellBtnText: { color: '#FFFFFF', fontWeight: '900', fontSize: 16, textTransform: 'uppercase' },
  premiumUpsellSubtext: {
    fontSize: 12,
    color: '#94A3B8',
    textAlign: 'center',
    fontWeight: '600',
    lineHeight: 18,
  },
});

export default styles;
